baseurl: ""
url: http://abdotalaat.github.io


title: Abdotalaat
description: A blog about programming.




authors:
    erik:
        name: Abdo Talaat
        signature: Abdo
        # Icons
        email_address: abdotalaatfcih@gmail.com
        bitbucket:
        dribbble:
        facebook:
        flickr:
        github: 
        google_plus: 
        gravatar_hash: 
        instagram:
        linkedin: 
        pinterest: 
        reddit: 
        stack_exchange: 
        steam: 
        tumblr: 
        twitter: 
        wordpress:
        youtube: 

paginate: 5
paginate_path: "blog/page:num"

kramdown:
    input: GFM

sass:
    sass_dir: _sass
    style: :compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
