baseurl: ""
url: http://abdotalaat.github.io
#baseurl: /technicalrex.com
#url: http://abdotalaat.github.io

title: Technical Rex
description: A site about programming, business, and dinosaurs. ROAR!

google_analytics: UA-62666024-3

tag_permalink_style: pretty
tag_page_layout: tag
tag_page_dir: tag

tag_descriptions:
    pegger: >
        Pegger is a turn-based peg jumping game. The following posts form a tutorial
        series covering data modeling, API design, and server- and client-side implementation
        using Java, Google App Engine, Bootstrap, and AngularJS.

authors:
    erik:
        name: Abdo Talaat
        signature: Abdo
        # Icons
        email_address: abdotalaatfcih@gmail.com
        bitbucket:
        dribbble:
        facebook:
        flickr:
        github: 
        google_plus: 
        gravatar_hash: 
        instagram:
        linkedin: 
        pinterest: 
        reddit: 
        stack_exchange: 
        steam: 
        tumblr: 
        twitter: 
        wordpress:
        youtube: 

paginate: 5
paginate_path: "blog/page:num"

kramdown:
    input: GFM

sass:
    sass_dir: _sass
    style: :compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
